### ISSUE TITLE
What do the decibel and qpm in the png_images folder represent respectively? 

### ISSUE THREAD

**Issue by IKOL111** [benjaminlewis-afrl/SAMPLE_dataset_public#1]
Hello! Thank you very much for your work! I have a question, may I ask What do the decibel and qpm in the png_images folder mean? thank you!

**Comment by benjaminlewis-afrl** [comment]
Hello! Both sets of images are formed from the raw .mat files by taking the absolute value, removing bright outliers, and normalizing between 0 and 1. Then: 
- For Decibel, we apply 20 * log_10(x) to each pixel, although a small epsilon is added to x for numerical stability. 
- For QPM, we apply sqrt(x) to each pixel. QPM stands for 'quarter power magnitude'. I'm not sure why it's called quarter power but is only half power/square root, but it's a common normalization. 

After applying the respective normalizations, the resulting images are scaled to unsigned ints between 0 and 255 and saved as PNG files.

**Comment by IKOL111** [comment]
> Okay, thank you very much for your reply!
