### ISSUE TITLE
Paired SAR and EO datasets.

### ISSUE THREAD

**Issue by tongxiaozhong14** [benjaminlewis-afrl/SAMPLE_dataset_public#2]
I am pleased to see your published work, please can you make public the dataset SAMPLE_dataset_public mentioned in the paper "Assessment of Various Multimodal Fusion Approaches Using Synthetic Aperture Radar (SAR) and Electro-Optical (EO) Imagery for Vehicle Classification via Neural Networks", the visible and SAR data mentioned in the paper "Assessment of Various Multimodal Fusion Approaches Using Synthetic Aperture Radar (SAR) and Electro-Optical (EO) Imagery for Vehicle Classification via Neural Networks" are paired, could you please provide me with the paired SAR and EO data? Thank you very much!

**Comment by benjaminlewis-afrl** [comment]
Hello,

My apologies, but there are no plans to release the EO imagery at this time.

Thank you!
